### ISSUE TITLE
Cannot install with Python 3.5

### ISSUE THREAD

**Issue by thinca** [Kuniwak/vint#137] opened 2015-10-25 20:44 UTC
![](https://i.gyazo.com/8e82502e80d59698d7853198f4d4913f.png)

**Comment by Kuniwak** [comment] 2015-10-26 00:36
This problem is caused by enum34 package.

https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35

It can be resolved by a patch like [it](https://github.com/xmikos/reparser/pull/2/files).

I'm gonna fix it later, but probably it is fast if you send PR to vint.

**Closed** 2015-11-12 01:07 UTC
